// =====================================================================
// Declaração de tipos para lucide-react
// (o pacote distribuído no registry usado não inclui .d.ts próprios)
// =====================================================================
declare module 'lucide-react' {
  import type { ComponentType, SVGProps } from 'react';

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }

  export type LucideIcon = ComponentType<LucideProps>;

  export const AlarmClock: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const AlignLeft: LucideIcon;
  export const Archive: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowDownToLine: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRightLeft: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowUpFromLine: LucideIcon;
  export const Ban: LucideIcon;
  export const BarChart2: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Bell: LucideIcon;
  export const Bot: LucideIcon;
  export const Braces: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarClock: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const CircleDot: LucideIcon;
  export const Clock: LucideIcon;
  export const Code2: LucideIcon;
  export const Copy: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Download: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const FileAudio: LucideIcon;
  export const FileSpreadsheet: LucideIcon;
  export const FileText: LucideIcon;
  export const Filter: LucideIcon;
  export const Flag: LucideIcon;
  export const FormInput: LucideIcon;
  export const Gauge: LucideIcon;
  export const GitBranch: LucideIcon;
  export const Globe: LucideIcon;
  export const GripVertical: LucideIcon;
  export const Hand: LucideIcon;
  export const Hash: LucideIcon;
  export const Headset: LucideIcon;
  export const History: LucideIcon;
  export const Inbox: LucideIcon;
  export const Info: LucideIcon;
  export const KanbanSquare: LucideIcon;
  export const KeyRound: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const LayoutTemplate: LucideIcon;
  export const List: LucideIcon;
  export const ListFilter: LucideIcon;
  export const ListOrdered: LucideIcon;
  export const Loader2: LucideIcon;
  export const LogIn: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const Megaphone: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const MessageSquareText: LucideIcon;
  export const Mic: LucideIcon;
  export const Minus: LucideIcon;
  export const PanelRightClose: LucideIcon;
  export const PanelRightOpen: LucideIcon;
  export const Paperclip: LucideIcon;
  export const Pause: LucideIcon;
  export const Pencil: LucideIcon;
  export const Phone: LucideIcon;
  export const Play: LucideIcon;
  export const PlayCircle: LucideIcon;
  export const Plug: LucideIcon;
  export const Plus: LucideIcon;
  export const QrCode: LucideIcon;
  export const Quote: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Save: LucideIcon;
  export const ScrollText: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Settings2: LucideIcon;
  export const Share2: LucideIcon;
  export const Sheet: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Square: LucideIcon;
  export const Star: LucideIcon;
  export const StickyNote: LucideIcon;
  export const Tag: LucideIcon;
  export const TagIcon: LucideIcon;
  export const Tags: LucideIcon;
  export const Timer: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Type: LucideIcon;
  export const Unplug: LucideIcon;
  export const Upload: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const User: LucideIcon;
  export const UserCheck2: LucideIcon;
  export const UserCircle: LucideIcon;
  export const UserPlus: LucideIcon;
  export const Users: LucideIcon;
  export const Video: LucideIcon;
  export const Webhook: LucideIcon;
  export const Workflow: LucideIcon;
  export const X: LucideIcon;
  export const Youtube: LucideIcon;
  export const ZoomIn: LucideIcon;
  export const ZoomOut: LucideIcon;
}
